### ISSUE TITLE
Encrypt connection (HTTPS)

### ISSUE THREAD

**Issue by rugk** [marcosdiez/shareviahttp#23]
It would be nice if the app could encrypt the connection. Transferring files via unencrypted corrections is irresponsible.
It could even easily user self signed certificates when the fingerprint of the cert is submitted via the QR code.

**Comment by marcosdiez** [comment]
self signed certificates are just as irresponsible as unencrypted connections, for they are susseptible to the same man in the middle attack (and therefore eavesdropping)

also, this usually works only on LAN because phones don't have public IPs
you can easily be sure that your LAN is safe enough. If not, you can set your phone to be an encrypted AP and send the file using that. 

last but not least, sending the fingerprint of the cert via QR code is not hard but one would need a specific client to download the file, which would end the beauty of this app.

Therefore I don't feel incline to implement this.
