### ISSUE TITLE
accepts any URL

### ISSUE THREAD

**Issue by calestyo** [marcosdiez/shareviahttp#28]
Hi.

Really a wonderful app, something I've been looking for quite long (I hated all the non-open-source and bloated solutions).

I'll open a number of issues with ideas for improvement :-)

The app will allow any URL, when accessing the http server.
E.g. not just:
http:/192.168.0.1:9999/
but also
http:/192.168.0.1:9999/foobar

Not really an immediate problem but still I'd feel better if it wouldn't allow that (one could think of attackers somehow trying to get access to non served files e.g. http:/192.168.0.1:9999/../../etc/passwd or so ;-)

Cheers,
Chris.

**Comment by mdiez-modus** [comment]
Hi!

That is not a problem because
a) Android does not have critical files like /etc/passwd
b) The app does not resolve file paths
That means whatever you share, is what you will get, only one file at a time.
And for your convenience, the target file will whichever name you want.

So if I am sharing a wedding photo I could do

wget --trust-server-names http://192.168.0.1:9999/wedding_photos.zip 

So that is not a bug, but a feature.

**Comment by marcosdiez** [comment]
Hi!

That is not a problem because
a) Android does not have critical files like /etc/passwd
b) The app does not resolve file paths
That means whatever you share, is what you will get, only one file at a time.
And for your convenience, the target file will whichever name you want.

So if I am sharing a wedding photo I could do

wget --trust-server-names http://192.168.0.1:9999/wedding_photos.zip

So that is not a bug, but a feature.
