### ISSUE TITLE
securiy: http server seems to bind to all addresses

### ISSUE THREAD

**Issue by calestyo** [marcosdiez/shareviahttp#30]
Hey.

When I share a file, it display e.g.
http://192.168.0.1:9999/

And there is a small hint about "it always works with a non blocked IPv6"...
There's also the change IP address button, which shows the devices addresses and kinda implies it would only listen on the selected address.

However, even when I have e.g. http://192.168.0.1:9999/ selected, the file is still accessible via e.g. a globally scoped IPv6 address (which, depending on the firewall) may then *really* be accessible globally.

Can't you accept requests only from the selected IP address/port?
Perhaps you could add the wildcard interfaces 0.0.0.0 and :: as an option to bind to any address when the user really wants.

Cheers,
Chris.

**Comment by marcosdiez** [comment]
That's not a bug, it's a feature.
The idea of binding to all IPs means it will do as most as it can to share your data. So whichever IP you choose it should work.

If you are on 4G, your network operator firewalls you so you don't get any connection anyway.
If you are on WiFi, your home router does not allow incoming connections anyway. (even with IPv6)
And if it does, it's because you configured it which may mean you wanted that.

It's a simple file sharing tool. Not nginx.

**Comment by calestyo** [comment]
Well **if** the ISP does the right thing... and **if** the router is doing the right thing (or not even hacked).
