### ISSUE TITLE
allow for other containers for multi file

### ISSUE THREAD

**Issue by calestyo** [marcosdiez/shareviahttp#33]
Currently, when you serve multiple files, you do so as ZIP.

This has typically the disadvantage that files must be actually ZIPped... so at least this should happen with the worst compression level...

An alternative could be tar... with that it should be possible to stream the multi file archive.

**Comment by marcosdiez** [comment]
With my phone I can get about 5 MB/s with creating a ZIP on the fly. I actually compress as much as I can.
This way the data will not use much space in the target device.
And zip is the most backward compatible archive I can think of.
Even Windows XP opens them natively.
And those who want tar can write a one line shell script to convert zip 2 tar.

something like 

`curl http://192.168.42.42:9999/ | unzip | tar Jcf > target_file.tar.xz`

**Comment by calestyo** [comment]
Well that would have been the example of some on-the-fly generated tar...

no waste of CPU for the compression... and no waste of space for creating a new file,... as the tar is created as you send.

**Comment by calestyo** [comment]
and of course one can convert the zip to a tar on the client (e.g. PC), but that's not what was the idea here... the idea was to lower the CPU load and storage use on the server (i.e. the phone)....

**Comment by marcosdiez** [comment]
Yes, but sometimes if you compress you get a higher throughput (when the bandwidth is the bottleneck).
Again, whoever has such problems can easily solve it. The normal user will just store the file, so a "highly" compressed zip is good for him/her, because it open anywhere.

This app is more than 8 years old and I never received such requests.
Maybe you misunderstood the use of the app.
Maybe what you need is https://play.google.com/store/apps/details?id=berserker.android.apps.sshdroid 
It's an ssh server for android.

This way you can copy files to and from it using scp.
Or you can ssh to it and generate tar files (or tar.gz or tar.bz2 or tar.xz).
You can even pipe the output, so the archive generation can be done on the fly.
And to compress you can choose between using your phone or your pc, just by changing the order of the `| xz -9` part in the command line
And it supports SSH authentication, security keys and so on.
Last but not least, if you are rooted, it can even bind on port 22.

maybe that is what you need.
