### ISSUE TITLE
Speed is 1MB/s?

### ISSUE THREAD

**Issue by HKalbasi** [marcosdiez/shareviahttp#62]
Is it common that my download speed is almost 1MB/s? My Internet speed is sometimes faster with the same wi-fi modem. Is problem with me or with the app?

**Comment by marcosdiez** [comment]
The problem is not related to my app.

The app works like this:

- you share one (or many) files through my app
- my app launches, listens to the HTTP port and receives the list of files to be shared from the source app
- when and only when a device connects to the HTTP port of my app, my app requests the file from the source app and streams it via HTTP to your target device.
- if and only if you shared a list of files, my app generates a zip file on the file and streams it on the fly to the HTTP server

hence if things are slow it will be either
- because the source app can't provide data fast enough 
- because the the target device can't download quick enough

**Comment by HKalbasi** [comment]
Thank you for quick response!
What is the source app? File manager or the OS? (I am using the "pick button" inside the app and share one file) And what I can do in this case?

**Comment by marcosdiez** [comment]
I would not blame the OS.
It's either your hardware (phone) or the source app.
Source app is the app in which you click on the "share" button.

Try sharing something else. Something large, like a video from the video/gallery app.

If that is slow as well, maybe you need a new phone :)

**Comment by HKalbasi** [comment]
Oh, Seems it is related to my wifi... With phone's hotspot speed is 5MB/s.
